apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chat-secret
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: chat-secret
    creationPolicy: Owner
  dataFrom:
  - find:
      path: /commitme/v3/prod/chat-server
      name:
        regexp: ".*"
    rewrite:
    - regexp:
        source: "/commitme/v3/prod/chat-server/(.*)"
        target: "$1"
