apiVersion: apps/v1
kind: Deployment
metadata:
  name: team15-be
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team15-be
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: team15-be
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: be
        image: 248312021437.dkr.ecr.ap-northeast-2.amazonaws.com/commit-me/web-server:latest
        envFrom:
        - secretRef:
            name: be-secret
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
