apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: be-secret
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: be-secret
    creationPolicy: Owner
  dataFrom:
  - find:
      path: /commitme/v2/prod/be-server
      name:
        regexp: ".*"
    rewrite:
    - regexp:
        source: "_commitme_v2_prod_be-server_(.*)"
        target: "$1"
