apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- external-secret.yaml
- configmap.yaml

images:
- name: 248312021437.dkr.ecr.ap-northeast-2.amazonaws.com/commit-me/web-server
  newTag: "a031f3aa25b70b82971bf83e9c3f2d97715edb25"
