apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 15team-be
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/15-team-service-cloud.git
    targetRevision: main
    path: gitops/apps/be
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
